---
name: securefix
# on: push
on: pull_request
jobs:
  test:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - run: npm i -g prettier
      - run: prettier -w .

      - uses: csm-actions/securefix-action@59717c1355b1ab4a7015f8b17e5337db9a66ef4e # v0.5.7
        with:
          app_id: ${{vars.TEST_CLIENT_APP_ID}}
          app_private_key: ${{secrets.TEST_CLIENT_PRIVATE_KEY}}
          server_repository: test-server
