---
name: securefix
# on: push
on: pull_request
jobs:
  test:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - run: npm i -g prettier
      - run: prettier -w .

      - uses: csm-actions/securefix-action@4d885e1bcb71f4f110215c833002ce9fa0ee0fa6 # v0.6.0
        with:
          app_id: ${{vars.TEST_CLIENT_APP_ID}}
          app_private_key: ${{secrets.TEST_CLIENT_PRIVATE_KEY}}
          server_repository: test-server
