---
name: securefix
# on: push
on: pull_request
jobs:
  test:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - run: npm i -g prettier
      - run: prettier -w .

      - uses: csm-actions/securefix-action@1301ea990d2c6db9e1bfb3078c925f0d95518080 # v0.5.5
        with:
          app_id: ${{vars.TEST_CLIENT_APP_ID}}
          app_private_key: ${{secrets.TEST_CLIENT_PRIVATE_KEY}}
          server_repository: test-server
